"use client";
import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { GlassPanel } from "@/components/ui/glass-panel";
import { useWorkspace } from "@/features/data/use-workspace";
import { workspaceRepository } from "@/features/data/repository";
import { addTodo, deleteTodo, toggleTodo, updateTodo } from "@/features/todos/model";

export function TasksPage(){const data=useWorkspace();const[title,setTitle]=useState("");const[view,setView]=useState<"list"|"kanban">("list");const add=()=>{if(title.trim()){workspaceRepository.set(addTodo(data,{title:title.trim(),dueDate:new Date().toLocaleDateString("sv-SE"),projectId:null}));setTitle("")}};const groups=["todo","in-progress","done"] as const;return <div className="page-stack"><header className="page-heading"><p>任务中枢</p><h1>任务</h1><span>收集、安排并完成每天真正重要的事项。</span></header><div className="toolbar"><label><input value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="快速添加任务…"/></label><button className="primary-action" onClick={add}><Plus/>添加</button><button onClick={()=>setView(view==="list"?"kanban":"list")}>{view==="list"?"看板":"列表"}</button></div>{view==="list"?<GlassPanel className="v2-list">{data.todos.map(t=><div className={`v2-task priority-${t.priority}`} key={t.id}><button onClick={()=>workspaceRepository.set(toggleTodo(data,t.id))}>{t.completed?"✓":"○"}</button><span>{t.title}</span><select value={t.priority} onChange={e=>workspaceRepository.set(updateTodo(data,t.id,{priority:e.target.value as typeof t.priority}))}><option value="low">低</option><option value="medium">中</option><option value="high">高</option><option value="urgent">紧急</option></select><button onClick={()=>workspaceRepository.set(deleteTodo(data,t.id))}><Trash2/></button></div>)}</GlassPanel>:<div className="kanban-grid">{groups.map(status=><GlassPanel key={status} className="kanban-column"><h2>{{todo:"待办","in-progress":"进行中",done:"已完成"}[status]}</h2>{data.todos.filter(t=>(t.status==="done"||t.completed?"done":t.status)===status).map(t=><button key={t.id} onClick={()=>workspaceRepository.set(updateTodo(data,t.id,{status:status==="todo"?"in-progress":"done",completed:status!=="todo"}))}>{t.title}</button>)}</GlassPanel>)}</div>}</div>}
