"use client";

import { ExternalLink, FolderOpen, GitBranch, Terminal, Trash2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { GlassPanel, SectionTitle } from "@/components/ui/glass-panel";
import { useWorkspace } from "@/features/data/use-workspace";
import { workspaceRepository } from "@/features/data/repository";
import { addTodo, deleteTodo, toggleTodo } from "@/features/todos/model";
import { openLaunch } from "@/lib/open-launch";

export function ProjectDetail({ id }: { id: string }) {const data=useWorkspace();const project=data.projects.find(item=>item.id===id);const [title,setTitle]=useState("");if(!project)return <div className="page-stack"><GlassPanel className="empty-state"><h1>未找到项目</h1><Link href="/projects">返回项目列表</Link></GlassPanel></div>;const actions=[{label:"打开文件夹",icon:FolderOpen,enabled:!!project.rootPath,launch:{type:"local-path" as const,path:project.rootPath}},{label:"打开 Terminal",icon:Terminal,enabled:!!project.rootPath,launch:{type:"custom-command" as const,executable:"open",args:["-a","Terminal",project.rootPath]}},{label:"打开 Codex",icon:ExternalLink,enabled:!!project.rootPath,launch:{type:"custom-command" as const,executable:"codex",args:[project.rootPath]}},{label:"打开 GitHub",icon:GitBranch,enabled:!!project.githubUrl,launch:{type:"website" as const,url:project.githubUrl||"https://github.com"}}];const todos=data.todos.filter(todo=>todo.projectId===id);return <div className="page-stack"><header className="page-heading"><p>项目共鸣</p><h1>{project.name}</h1><span>{project.description||project.rootPath||"配置项目详情后即可使用启动操作。"}</span></header><div className="action-grid">{actions.map(({label,icon:Icon,enabled,launch})=><button key={label} disabled={!enabled} title={enabled?label:"请先在项目或设置中配置路径"} onClick={()=>void openLaunch(launch)}><Icon/>{label}<small>{enabled?"已就绪":"未配置"}</small></button>)}</div><GlassPanel className="project-todos"><SectionTitle>项目待办</SectionTitle><form onSubmit={e=>{e.preventDefault();if(title.trim()){workspaceRepository.set(addTodo(data,{title:title.trim(),dueDate:null,projectId:id}));setTitle("")}}}><input aria-label="新项目待办" value={title} onChange={e=>setTitle(e.target.value)} placeholder="添加项目任务…"/><button className="primary-action">添加</button></form>{todos.map(todo=><div className="todo-row" key={todo.id}><button onClick={()=>workspaceRepository.set(toggleTodo(data,todo.id))}>{todo.completed?"✓":"○"}</button><span>{todo.title}</span><button aria-label={`删除 ${todo.title}`} onClick={()=>workspaceRepository.set(deleteTodo(data,todo.id))}><Trash2/></button></div>)}{!todos.length&&<div className="empty-compact">暂无项目任务。</div>}</GlassPanel></div>}
